"""create orders and order_items tables

Revision ID: 3f470611d435
Revises: 070dc98c1f60
Create Date: 2026-05-14 22:10:59.738949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f470611d435'
down_revision: Union[str, Sequence[str], None] = '070dc98c1f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Comando para criar as tabelas "orders" e "order_items" com os relacionamentos apropriados.

# A tabela "orders" armazena informações sobre cada pedido, incluindo o ID do usuário, status, total e data de criação.
# A tabela "order_items" armazena os itens de cada pedido, incluindo o ID do pedido, ID do produto, quantidade e preço. Ambas as tabelas possuem chaves estrangeiras para garantir a integridade referencial com as tabelas "users" e "products".
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Cria a tabela de pedidos
    op.create_table('orders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('total', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)

    # Cria a tabela de itens do pedido
    op.create_table('order_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('price', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id']),
        sa.ForeignKeyConstraint(['product_id'], ['products.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)

    # ### end Alembic commands ###

# Comando para remover as tabelas "orders" e "order_items" e os índices associados. As tabelas são removidas na ordem inversa para evitar problemas de dependência devido às chaves estrangeiras.
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
     # Remove as tabelas na ordem inversa
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
     # ### end Alembic commands ###
